[build]
  command = "npm run build"
  publish = "dist"

  [build.environment]
    REACT_APP_BACKEND_URL = "https://default-backend-url.example.com" # Placeholder URL

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200