[build]
  command = "npm run build"
  publish = "dist"

  [build.environment]
    REACT_APP_BACKEND_URL = "https://41567978d71fe4.lhr.life"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200